spring:
  datasource:
#    url: jdbc:sqlserver://1.15.46.209:1433;DatabaseName=DB_TeachingMS
#    username: sa
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/DB_TeachingMS?serverTimezone=GMT%2B8

# 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
logging:
  file:
    name: spring.log
    path: /Users/qiuhan/IdeaProjects/TeachingMS/log
